<a href="https://colab.research.google.com/github/saksham3232/DS-YT/blob/main/pandas/1-series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Series
A Series is a one-dimensional labeled array capable of holding any data type. The axis labels are collectively called the index.

# Creating Series
There are multiple ways to create a pandas Series:

In [1]:
import numpy as np
import pandas as pd

In [10]:
labels = ['a', 'b', 'c']
my_list = [10, 20, 30]
my_arr = np.array([10, 20, 30])
d = {'a':10, 'b':20,'c':30}

In [11]:
pd.Series(my_list, index=labels)

a    10
b    20
c    30
dtype: int64

In [12]:
pd.Series(my_arr)

0    10
1    20
2    30
dtype: int64

In [13]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64