<a href="https://colab.research.google.com/github/saksham3232/DS-YT/blob/main/pandas/8-FeatureExtraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [22]:
# Loading the data
df = pd.read_csv(r'anime.csv')

In [23]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [24]:
df.loc[2]['Title']

'Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members'

In [25]:
def extract_episodes(txt):
  check = False
  data = ''
  for i in txt:
    if i == ')':
      check = False
      return data
    if check == True:
      data += i
    if i == '(':
      check = True

In [27]:
df['Episodes'] = df['Title'].apply(extract_episodes)

In [29]:
df['Episodes'] = df['Episodes'].str.replace(" eps", "")

In [30]:
df

    Rank                                              Title  Score Episodes
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10       64
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07       24
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06       13
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06       51
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05       10
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04       51
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04        1
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04      148
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04       13
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03       13
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03        2
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02      110
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99       13
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99       13
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98       12
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94      201
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94        1
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93       22
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93       24
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91       25
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91        1
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89        1
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88        7
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88       14
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87       74
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84        1
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84        1
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83       12
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83        1
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82       24
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82       23
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81       12
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81       26
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80       13
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80       16
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79       11
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79        1
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79       11
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78       10
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78        1
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77       26
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77       12
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76       75
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75       26
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75       26
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74       24
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73       10
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72       12
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71       12
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71        4

In [31]:
type(df.loc[0]['Episodes'])

str

In [33]:
df['Episodes'] = df['Episodes'].astype(int)

In [34]:
df

    Rank                                              Title  Score  Episodes
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10        64
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07        24
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06        13
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06        51
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05        10
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04        51
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04         1
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04       148
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04        13
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03        13
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03         2
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02       110
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99        13
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99        13
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98        12
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94       201
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94         1
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93        22
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93        24
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91        25
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91         1
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89         1
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88         7
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88        14
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87        74
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84         1
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84         1
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83        12
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83         1
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82        24
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82        23
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81        12
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81        26
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80        13
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80        16
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79        11
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79         1
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79        11
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78        10
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78         1
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77        26
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77        12
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76        75
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75        26
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75        26
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74        24
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73        10
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72        12
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71        12
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71         4

In [35]:
# make a new column for timestamp
df.loc[0]['Title']

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

In [38]:
def extraction_time(txt):
  check = False
  data = ""
  for i in range(len(txt)):
    if txt[i] == ')':
      for j in range(i+1, i+20):
        data += txt[j]

      return data

In [40]:
df['Total Time'] = df['Title'].apply(extraction_time)

In [42]:
df.head()

,Rank,Title,Score,Episodes,Total Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [43]:

from dateutil.relativedelta import relativedelta
from datetime import datetime

def calculate_total_months(period):
    try:
        start_str, end_str = period.split(' - ')
        start_date = datetime.strptime(start_str, '%b %Y')
        end_date = datetime.strptime(end_str, '%b %Y')
        r = relativedelta(end_date, start_date)
        return r.years * 12 + r.months + 1  # +1 to include the starting month
    except:
        return None

df['Months'] = df['Total Time'].apply(calculate_total_months)

In [44]:
df.head()

,Rank,Title,Score,Episodes,Total Time,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4

In [45]:
# which anime has the highest score
df[df['Score'] == df['Score'].max()]['Title']

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
Name: Title, dtype: object

In [47]:
# give top 5 highest scoring anime
df['Title'].head()

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Name: Title, dtype: object

In [48]:
# anime has highest episode count
df[df['Episodes'] == df['Episodes'].max()]

,Rank,Title,Score,Episodes,Total Time,Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,48

In [49]:
df.head()

,Rank,Title,Score,Episodes,Total Time,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4

In [50]:
# animes with top 5 episode count
df.sort_values(by='Episodes', ascending=False)['Title'].head()

15    GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...
7     Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...
11    Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...
42    Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...
24    MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...
Name: Title, dtype: object

In [57]:
# which is the longest running anime
df[df['Months'] == df['Months'].max()]['Title']

11    Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...
Name: Title, dtype: object